/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health check endpoint
		 * @description Returns the status and local/ISO timestamps.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Service is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["HealthResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/metrics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Collect telemetry and usage metrics
		 * @description Stores performance and WCAG compliance data to MongoDB.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["MetricPayload"];
				};
			};
			responses: {
				/** @description Metric captured successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Invalid metrics payload */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/analytics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Fetch analytics trends
		 * @description Aggregates historical metrics for Feature Popularity, User Engagement, Accessibility Compliance, and Performance.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful retrieval */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["AnalyticsResult"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/generateImage": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generate a single cover image
		 * @description Renders a custom PNG cover using the canvas engine.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ImageParams"];
				};
			};
			responses: {
				/** @description Rendered PNG cover image */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"image/png": string;
					};
				};
				/** @description Validation failed (e.g. low contrast, invalid size, too long text) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationErrorResponse"];
					};
				};
				/** @description Internal rendering or database error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/generateGif": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generate an animated GIF slideshow
		 * @description Renders a multi-frame animated GIF cover sequence using the pure-Go canvas engine.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["GifParams"];
				};
			};
			responses: {
				/** @description Rendered animated GIF slideshow */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"image/gif": string;
					};
				};
				/** @description Validation failed (e.g. less than 2 slides, low contrast, invalid size) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationErrorResponse"];
					};
				};
				/** @description Internal rendering error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/generateCarousel": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Submit a carousel generation job
		 * @description Enqueues a carousel deck to be rendered into a multi-page PDF and PNG archive asynchronously.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["CarouselParams"];
				};
			};
			responses: {
				/** @description Carousel job accepted */
				202: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @description The unique Job ID for status polling. */
							id: string;
						};
					};
				};
				/** @description Carousel validation failed */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/getJobStatus": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Poll status of a bulk generation batch
		 * @description Returns progress counter, enqueued time, and completed image URLs for a batch Job ID.
		 */
		get: {
			parameters: {
				query: {
					jobId: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Current status of the job */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["JobStatusResponse"];
					};
				};
				/** @description Missing jobId query parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Job ID not found */
				444: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		HealthResponse: {
			/** @example success */
			status: string;
			/** Format: date-time */
			timestamp: string;
			data: {
				localTime: string;
				isoTime: string;
			};
		};
		ImageParams: {
			/** @example 1200 */
			width: number;
			/** @example 627 */
			height: number;
			/** @example #374151 */
			backgroundColor: string;
			/** @example #F9FAFB */
			textColor: string;
			/**
			 * @example Montserrat
			 * @enum {string}
			 */
			font: "Montserrat" | "Roboto" | "Lato" | "Playfair Display" | "Open Sans";
			/** @example Welcome */
			title: string;
			/** @example Cover Craft */
			subtitle?: string;
			/**
			 * @description Whether to render an inset border around the cover (defaults to false)
			 * @example false
			 */
			hasBorder?: boolean;
			/** @example cover */
			filename: string;
		};
		GifSlideParams: {
			/** @example Welcome */
			title: string;
			/** @example Cover Craft */
			subtitle?: string;
			/**
			 * @example Montserrat
			 * @enum {string}
			 */
			font: "Montserrat" | "Roboto" | "Lato" | "Playfair Display" | "Open Sans";
			/**
			 * @description Slide text color. If omitted, a random WCAG AA compliant color is generated.
			 * @example #F9FAFB
			 */
			textColor?: string;
			/**
			 * @description Whether to render an inset border around the slide (defaults to false)
			 * @example false
			 */
			hasBorder?: boolean;
		};
		GifParams: {
			/** @example 1200 */
			width: number;
			/** @example 627 */
			height: number;
			/** @example #374151 */
			backgroundColor: string;
			/**
			 * @default 1500
			 * @example 1500
			 * @enum {integer}
			 */
			delayMs: 1000 | 1500 | 2000 | 3000;
			slides: components["schemas"]["GifSlideParams"][];
			/** @example slideshow */
			filename?: string;
		};
		CarouselSlideParams: {
			/** @example Building Scalable Systems */
			title: string;
			/**
			 * @description Optional paragraph or subtitle commentary
			 * @example Architectural principles for high-throughput distributed systems.
			 */
			subtitle?: string;
			/**
			 * @description Optional bulleted or numbered list items
			 * @example [
			 *       "Design for horizontal scalability",
			 *       "Decouple compute from storage",
			 *       "Enforce strict API contracts"
			 *     ]
			 */
			listItems?: string[];
			/**
			 * @default left
			 * @example left
			 * @enum {string}
			 */
			textAlign: "left" | "center" | "right";
			/**
			 * @default top
			 * @example top
			 * @enum {string}
			 */
			verticalAlign: "top" | "center" | "bottom";
			/**
			 * @description Slide background color override. If omitted, uses deck backgroundColor.
			 * @example #1E293B
			 */
			backgroundColor?: string;
			/**
			 * @description Slide text color override. If omitted, uses deck textColor.
			 * @example #F8FAFC
			 */
			textColor?: string;
		};
		CarouselParams: {
			/** @example 1080 */
			width: number;
			/** @example 1350 */
			height: number;
			/** @example #0F172A */
			backgroundColor: string;
			/** @example #F8FAFC */
			textColor: string;
			/**
			 * @example Montserrat
			 * @enum {string}
			 */
			font: "Montserrat" | "Roboto" | "Lato" | "Playfair Display" | "Open Sans";
			/**
			 * @default none
			 * @example single
			 * @enum {string}
			 */
			borderStyle: "none" | "single" | "double";
			/** @example @username */
			authorHandle?: string;
			/**
			 * @default bottom-left
			 * @example bottom-left
			 * @enum {string}
			 */
			authorHandlePosition:
				| "bottom-left"
				| "bottom-right"
				| "top-left"
				| "top-right";
			/**
			 * @default true
			 * @example true
			 */
			showSlideNumbers: boolean;
			/**
			 * @default top-right
			 * @example top-right
			 * @enum {string}
			 */
			slideNumberPosition:
				| "top-right"
				| "bottom-right"
				| "top-left"
				| "bottom-left";
			slides: components["schemas"]["CarouselSlideParams"][];
			/** @example carousel */
			filename?: string;
		};
		ValidationError: {
			/** @example width */
			field: string;
			/** @example Width must be between 1 and 1400 */
			message: string;
		};
		ValidationErrorResponse: {
			/** @example Validation failed */
			error: string;
			details: components["schemas"]["ValidationError"][];
		};
		ErrorResponse: {
			/** @example Internal server error */
			error: string;
		};
		MetricPayload: {
			/** @example image_generated */
			event: string;
			/** Format: date-time */
			timestamp: string;
			/** @enum {string} */
			status: "success" | "error" | "validation_error";
			errorMessage?: string;
			size?: {
				width: number;
				height: number;
			};
			font?: string;
			hasBorder?: boolean;
			borderStyle?: string;
			titleLength?: number;
			subtitleLength?: number;
			contrastRatio?: number;
			/** @enum {string} */
			wcagLevel?: "AAA" | "AA" | "FAIL";
			duration?: number;
			clientDuration?: number;
			slideCount?: number;
			compileDuration?: number;
			fileSizeBytes?: number;
		};
		JobStatusResponse: {
			id: string;
			/** @enum {string} */
			status: "pending" | "processing" | "completed" | "failed";
			progress: number;
			total: number;
			results: string[];
			/** @description Base64 data URL or storage URL for the compiled carousel PDF document */
			pdfUrl?: string;
			error?: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/** @description Dashboard analytics details (feature popularity, accessibility, engagement) */
		AnalyticsResult: {
			userEngagement: Record<string, never>;
			featurePopularity: Record<string, never>;
			accessibilityCompliance: Record<string, never>;
			performanceMetrics: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
