// Package services provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package services

import (
	"time"
)

// Defines values for ImageParamsFont.
const (
	Lato            ImageParamsFont = "Lato"
	Montserrat      ImageParamsFont = "Montserrat"
	OpenSans        ImageParamsFont = "Open Sans"
	PlayfairDisplay ImageParamsFont = "Playfair Display"
	Roboto          ImageParamsFont = "Roboto"
)

// Defines values for JobStatusResponseStatus.
const (
	Completed  JobStatusResponseStatus = "completed"
	Failed     JobStatusResponseStatus = "failed"
	Pending    JobStatusResponseStatus = "pending"
	Processing JobStatusResponseStatus = "processing"
)

// Defines values for MetricPayloadStatus.
const (
	MetricPayloadStatusError           MetricPayloadStatus = "error"
	MetricPayloadStatusSuccess         MetricPayloadStatus = "success"
	MetricPayloadStatusValidationError MetricPayloadStatus = "validation_error"
)

// Defines values for MetricPayloadWcagLevel.
const (
	AA   MetricPayloadWcagLevel = "AA"
	AAA  MetricPayloadWcagLevel = "AAA"
	FAIL MetricPayloadWcagLevel = "FAIL"
)

// AnalyticsResult Dashboard analytics details (feature popularity, accessibility, engagement)
type AnalyticsResult struct {
	AccessibilityCompliance map[string]interface{} `json:"accessibilityCompliance"`
	FeaturePopularity       map[string]interface{} `json:"featurePopularity"`
	PerformanceMetrics      map[string]interface{} `json:"performanceMetrics"`
	UserEngagement          map[string]interface{} `json:"userEngagement"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Data struct {
		IsoTime   string `json:"isoTime"`
		LocalTime string `json:"localTime"`
	} `json:"data"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// ImageParams defines model for ImageParams.
type ImageParams struct {
	BackgroundColor string          `json:"backgroundColor"`
	Filename        string          `json:"filename"`
	Font            ImageParamsFont `json:"font"`
	Height          int             `json:"height"`
	Subtitle        *string         `json:"subtitle,omitempty"`
	TextColor       string          `json:"textColor"`
	Title           string          `json:"title"`
	Width           int             `json:"width"`
}

// ImageParamsFont defines model for ImageParams.Font.
type ImageParamsFont string

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	CreatedAt time.Time               `json:"createdAt"`
	Error     *string                 `json:"error,omitempty"`
	Id        string                  `json:"id"`
	Progress  int                     `json:"progress"`
	Results   []string                `json:"results"`
	Status    JobStatusResponseStatus `json:"status"`
	Total     int                     `json:"total"`
	UpdatedAt time.Time               `json:"updatedAt"`
}

// JobStatusResponseStatus defines model for JobStatusResponse.Status.
type JobStatusResponseStatus string

// MetricPayload defines model for MetricPayload.
type MetricPayload struct {
	ClientDuration *int     `json:"clientDuration,omitempty"`
	ContrastRatio  *float32 `json:"contrastRatio,omitempty"`
	Duration       *int     `json:"duration,omitempty"`
	ErrorMessage   *string  `json:"errorMessage,omitempty"`
	Event          string   `json:"event"`
	Font           *string  `json:"font,omitempty"`
	Size           *struct {
		Height int `json:"height"`
		Width  int `json:"width"`
	} `json:"size,omitempty"`
	Status         MetricPayloadStatus     `json:"status"`
	SubtitleLength *int                    `json:"subtitleLength,omitempty"`
	Timestamp      time.Time               `json:"timestamp"`
	TitleLength    *int                    `json:"titleLength,omitempty"`
	WcagLevel      *MetricPayloadWcagLevel `json:"wcagLevel,omitempty"`
}

// MetricPayloadStatus defines model for MetricPayload.Status.
type MetricPayloadStatus string

// MetricPayloadWcagLevel defines model for MetricPayload.WcagLevel.
type MetricPayloadWcagLevel string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Details []ValidationError `json:"details"`
	Error   string            `json:"error"`
}

// PostGenerateImagesJSONBody defines parameters for PostGenerateImages.
type PostGenerateImagesJSONBody = []ImageParams

// GetGetJobStatusParams defines parameters for GetGetJobStatus.
type GetGetJobStatusParams struct {
	JobId string `form:"jobId" json:"jobId"`
}

// PostGenerateImageJSONRequestBody defines body for PostGenerateImage for application/json ContentType.
type PostGenerateImageJSONRequestBody = ImageParams

// PostGenerateImagesJSONRequestBody defines body for PostGenerateImages for application/json ContentType.
type PostGenerateImagesJSONRequestBody = PostGenerateImagesJSONBody

// PostMetricsJSONRequestBody defines body for PostMetrics for application/json ContentType.
type PostMetricsJSONRequestBody = MetricPayload
