// Package services provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package services

import (
	"time"
)

// Defines values for CarouselParamsAuthorHandlePosition.
const (
	CarouselParamsAuthorHandlePositionBottomLeft  CarouselParamsAuthorHandlePosition = "bottom-left"
	CarouselParamsAuthorHandlePositionBottomRight CarouselParamsAuthorHandlePosition = "bottom-right"
	CarouselParamsAuthorHandlePositionTopLeft     CarouselParamsAuthorHandlePosition = "top-left"
	CarouselParamsAuthorHandlePositionTopRight    CarouselParamsAuthorHandlePosition = "top-right"
)

// Defines values for CarouselParamsBorderStyle.
const (
	Double CarouselParamsBorderStyle = "double"
	None   CarouselParamsBorderStyle = "none"
	Single CarouselParamsBorderStyle = "single"
)

// Defines values for CarouselParamsFont.
const (
	CarouselParamsFontLato            CarouselParamsFont = "Lato"
	CarouselParamsFontMontserrat      CarouselParamsFont = "Montserrat"
	CarouselParamsFontOpenSans        CarouselParamsFont = "Open Sans"
	CarouselParamsFontPlayfairDisplay CarouselParamsFont = "Playfair Display"
	CarouselParamsFontRoboto          CarouselParamsFont = "Roboto"
)

// Defines values for CarouselParamsSlideNumberPosition.
const (
	CarouselParamsSlideNumberPositionBottomLeft  CarouselParamsSlideNumberPosition = "bottom-left"
	CarouselParamsSlideNumberPositionBottomRight CarouselParamsSlideNumberPosition = "bottom-right"
	CarouselParamsSlideNumberPositionTopLeft     CarouselParamsSlideNumberPosition = "top-left"
	CarouselParamsSlideNumberPositionTopRight    CarouselParamsSlideNumberPosition = "top-right"
)

// Defines values for CarouselSlideParamsTextAlign.
const (
	CarouselSlideParamsTextAlignCenter CarouselSlideParamsTextAlign = "center"
	CarouselSlideParamsTextAlignLeft   CarouselSlideParamsTextAlign = "left"
	CarouselSlideParamsTextAlignRight  CarouselSlideParamsTextAlign = "right"
)

// Defines values for CarouselSlideParamsVerticalAlign.
const (
	CarouselSlideParamsVerticalAlignBottom CarouselSlideParamsVerticalAlign = "bottom"
	CarouselSlideParamsVerticalAlignCenter CarouselSlideParamsVerticalAlign = "center"
	CarouselSlideParamsVerticalAlignTop    CarouselSlideParamsVerticalAlign = "top"
)

// Defines values for GifParamsDelayMs.
const (
	N1000 GifParamsDelayMs = 1000
	N1500 GifParamsDelayMs = 1500
	N2000 GifParamsDelayMs = 2000
	N3000 GifParamsDelayMs = 3000
)

// Defines values for GifSlideParamsFont.
const (
	GifSlideParamsFontLato            GifSlideParamsFont = "Lato"
	GifSlideParamsFontMontserrat      GifSlideParamsFont = "Montserrat"
	GifSlideParamsFontOpenSans        GifSlideParamsFont = "Open Sans"
	GifSlideParamsFontPlayfairDisplay GifSlideParamsFont = "Playfair Display"
	GifSlideParamsFontRoboto          GifSlideParamsFont = "Roboto"
)

// Defines values for ImageParamsFont.
const (
	Lato            ImageParamsFont = "Lato"
	Montserrat      ImageParamsFont = "Montserrat"
	OpenSans        ImageParamsFont = "Open Sans"
	PlayfairDisplay ImageParamsFont = "Playfair Display"
	Roboto          ImageParamsFont = "Roboto"
)

// Defines values for JobStatusResponseStatus.
const (
	Completed  JobStatusResponseStatus = "completed"
	Failed     JobStatusResponseStatus = "failed"
	Pending    JobStatusResponseStatus = "pending"
	Processing JobStatusResponseStatus = "processing"
)

// Defines values for MetricPayloadStatus.
const (
	MetricPayloadStatusError           MetricPayloadStatus = "error"
	MetricPayloadStatusSuccess         MetricPayloadStatus = "success"
	MetricPayloadStatusValidationError MetricPayloadStatus = "validation_error"
)

// Defines values for MetricPayloadWcagLevel.
const (
	AA   MetricPayloadWcagLevel = "AA"
	AAA  MetricPayloadWcagLevel = "AAA"
	FAIL MetricPayloadWcagLevel = "FAIL"
)

// AnalyticsResult Dashboard analytics details (feature popularity, accessibility, engagement)
type AnalyticsResult struct {
	AccessibilityCompliance map[string]interface{} `json:"accessibilityCompliance"`
	FeaturePopularity       map[string]interface{} `json:"featurePopularity"`
	PerformanceMetrics      map[string]interface{} `json:"performanceMetrics"`
	UserEngagement          map[string]interface{} `json:"userEngagement"`
}

// CarouselParams defines model for CarouselParams.
type CarouselParams struct {
	AuthorHandle         *string                             `json:"authorHandle,omitempty"`
	AuthorHandlePosition *CarouselParamsAuthorHandlePosition `json:"authorHandlePosition,omitempty"`
	BackgroundColor      string                              `json:"backgroundColor"`
	BorderStyle          *CarouselParamsBorderStyle          `json:"borderStyle,omitempty"`
	Filename             *string                             `json:"filename,omitempty"`
	Font                 CarouselParamsFont                  `json:"font"`
	Height               int                                 `json:"height"`
	ShowSlideNumbers     *bool                               `json:"showSlideNumbers,omitempty"`
	SlideNumberPosition  *CarouselParamsSlideNumberPosition  `json:"slideNumberPosition,omitempty"`
	Slides               []CarouselSlideParams               `json:"slides"`
	TextColor            string                              `json:"textColor"`
	Width                int                                 `json:"width"`
}

// CarouselParamsAuthorHandlePosition defines model for CarouselParams.AuthorHandlePosition.
type CarouselParamsAuthorHandlePosition string

// CarouselParamsBorderStyle defines model for CarouselParams.BorderStyle.
type CarouselParamsBorderStyle string

// CarouselParamsFont defines model for CarouselParams.Font.
type CarouselParamsFont string

// CarouselParamsSlideNumberPosition defines model for CarouselParams.SlideNumberPosition.
type CarouselParamsSlideNumberPosition string

// CarouselSlideParams defines model for CarouselSlideParams.
type CarouselSlideParams struct {
	// BackgroundColor Slide background color override. If omitted, uses deck backgroundColor.
	BackgroundColor *string `json:"backgroundColor,omitempty"`

	// ListItems Optional bulleted or numbered list items
	ListItems *[]string `json:"listItems,omitempty"`

	// Subtitle Optional paragraph or subtitle commentary
	Subtitle  *string                       `json:"subtitle,omitempty"`
	TextAlign *CarouselSlideParamsTextAlign `json:"textAlign,omitempty"`

	// TextColor Slide text color override. If omitted, uses deck textColor.
	TextColor     *string                           `json:"textColor,omitempty"`
	Title         string                            `json:"title"`
	VerticalAlign *CarouselSlideParamsVerticalAlign `json:"verticalAlign,omitempty"`
}

// CarouselSlideParamsTextAlign defines model for CarouselSlideParams.TextAlign.
type CarouselSlideParamsTextAlign string

// CarouselSlideParamsVerticalAlign defines model for CarouselSlideParams.VerticalAlign.
type CarouselSlideParamsVerticalAlign string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GifParams defines model for GifParams.
type GifParams struct {
	BackgroundColor string            `json:"backgroundColor"`
	DelayMs         *GifParamsDelayMs `json:"delayMs,omitempty"`
	Filename        *string           `json:"filename,omitempty"`
	Height          int               `json:"height"`
	Slides          []GifSlideParams  `json:"slides"`
	Width           int               `json:"width"`
}

// GifParamsDelayMs defines model for GifParams.DelayMs.
type GifParamsDelayMs int

// GifSlideParams defines model for GifSlideParams.
type GifSlideParams struct {
	Font GifSlideParamsFont `json:"font"`

	// HasBorder Whether to render an inset border around the slide (defaults to false)
	HasBorder *bool   `json:"hasBorder,omitempty"`
	Subtitle  *string `json:"subtitle,omitempty"`

	// TextColor Slide text color. If omitted, a random WCAG AA compliant color is generated.
	TextColor *string `json:"textColor,omitempty"`
	Title     string  `json:"title"`
}

// GifSlideParamsFont defines model for GifSlideParams.Font.
type GifSlideParamsFont string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Data struct {
		IsoTime   string `json:"isoTime"`
		LocalTime string `json:"localTime"`
	} `json:"data"`
	Status    string    `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// ImageParams defines model for ImageParams.
type ImageParams struct {
	BackgroundColor string          `json:"backgroundColor"`
	Filename        string          `json:"filename"`
	Font            ImageParamsFont `json:"font"`

	// HasBorder Whether to render an inset border around the cover (defaults to false)
	HasBorder *bool   `json:"hasBorder,omitempty"`
	Height    int     `json:"height"`
	Subtitle  *string `json:"subtitle,omitempty"`
	TextColor string  `json:"textColor"`
	Title     string  `json:"title"`
	Width     int     `json:"width"`
}

// ImageParamsFont defines model for ImageParams.Font.
type ImageParamsFont string

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	CreatedAt time.Time `json:"createdAt"`
	Error     *string   `json:"error,omitempty"`
	Id        string    `json:"id"`

	// PdfUrl Base64 data URL or storage URL for the compiled carousel PDF document
	PdfUrl    *string                 `json:"pdfUrl,omitempty"`
	Progress  int                     `json:"progress"`
	Results   []string                `json:"results"`
	Status    JobStatusResponseStatus `json:"status"`
	Total     int                     `json:"total"`
	UpdatedAt time.Time               `json:"updatedAt"`
}

// JobStatusResponseStatus defines model for JobStatusResponse.Status.
type JobStatusResponseStatus string

// MetricPayload defines model for MetricPayload.
type MetricPayload struct {
	BorderStyle     *string  `json:"borderStyle,omitempty"`
	ClientDuration  *int     `json:"clientDuration,omitempty"`
	CompileDuration *int     `json:"compileDuration,omitempty"`
	ContrastRatio   *float32 `json:"contrastRatio,omitempty"`
	Duration        *int     `json:"duration,omitempty"`
	ErrorMessage    *string  `json:"errorMessage,omitempty"`
	Event           string   `json:"event"`
	FileSizeBytes   *int     `json:"fileSizeBytes,omitempty"`
	Font            *string  `json:"font,omitempty"`
	HasBorder       *bool    `json:"hasBorder,omitempty"`
	Size            *struct {
		Height int `json:"height"`
		Width  int `json:"width"`
	} `json:"size,omitempty"`
	SlideCount     *int                    `json:"slideCount,omitempty"`
	Status         MetricPayloadStatus     `json:"status"`
	SubtitleLength *int                    `json:"subtitleLength,omitempty"`
	Timestamp      time.Time               `json:"timestamp"`
	TitleLength    *int                    `json:"titleLength,omitempty"`
	WcagLevel      *MetricPayloadWcagLevel `json:"wcagLevel,omitempty"`
}

// MetricPayloadStatus defines model for MetricPayload.Status.
type MetricPayloadStatus string

// MetricPayloadWcagLevel defines model for MetricPayload.WcagLevel.
type MetricPayloadWcagLevel string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse struct {
	Details []ValidationError `json:"details"`
	Error   string            `json:"error"`
}

// GetGetJobStatusParams defines parameters for GetGetJobStatus.
type GetGetJobStatusParams struct {
	JobId string `form:"jobId" json:"jobId"`
}

// PostGenerateCarouselJSONRequestBody defines body for PostGenerateCarousel for application/json ContentType.
type PostGenerateCarouselJSONRequestBody = CarouselParams

// PostGenerateGifJSONRequestBody defines body for PostGenerateGif for application/json ContentType.
type PostGenerateGifJSONRequestBody = GifParams

// PostGenerateImageJSONRequestBody defines body for PostGenerateImage for application/json ContentType.
type PostGenerateImageJSONRequestBody = ImageParams

// PostMetricsJSONRequestBody defines body for PostMetrics for application/json ContentType.
type PostMetricsJSONRequestBody = MetricPayload
