/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health check endpoint
		 * @description Returns the status and local/ISO timestamps.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Service is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["HealthResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/metrics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Collect telemetry and usage metrics
		 * @description Stores performance and WCAG compliance data to MongoDB.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["MetricPayload"];
				};
			};
			responses: {
				/** @description Metric captured successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Invalid metrics payload */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/analytics": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Fetch analytics trends
		 * @description Aggregates historical metrics for Feature Popularity, User Engagement, Accessibility Compliance, and Performance.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Successful retrieval */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["AnalyticsResult"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/generateImage": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Generate a single cover image
		 * @description Renders a custom PNG cover using the canvas engine.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ImageParams"];
				};
			};
			responses: {
				/** @description Rendered PNG cover image */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"image/png": string;
					};
				};
				/** @description Validation failed (e.g. low contrast, invalid size, too long text) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationErrorResponse"];
					};
				};
				/** @description Internal rendering or database error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/generateImages": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Submit a bulk cover image generation batch
		 * @description Enqueues a batch of image parameters to be processed asynchronously by the background worker.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: {
				content: {
					"application/json": components["schemas"]["ImageParams"][];
				};
			};
			responses: {
				/** @description Batch job accepted */
				202: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": {
							/** @description The unique Job ID for status polling. */
							id: string;
						};
					};
				};
				/** @description Batch validation failed (e.g. empty batch or exceeds limit of 5) */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["ValidationErrorResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/jobStatus": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Poll status of a bulk generation batch
		 * @description Returns progress counter, enqueued time, and completed image URLs for a batch Job ID.
		 */
		get: {
			parameters: {
				query: {
					jobId: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Current status of the job */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["JobStatusResponse"];
					};
				};
				/** @description Missing jobId query parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Job ID not found */
				444: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		HealthResponse: {
			/** @example success */
			status: string;
			/** Format: date-time */
			timestamp: string;
			data: {
				localTime: string;
				isoTime: string;
			};
		};
		ImageParams: {
			/** @example 1200 */
			width: number;
			/** @example 627 */
			height: number;
			/** @example #374151 */
			backgroundColor: string;
			/** @example #F9FAFB */
			textColor: string;
			/**
			 * @example Montserrat
			 * @enum {string}
			 */
			font: "Montserrat" | "Roboto" | "Lato" | "Playfair Display" | "Open Sans";
			/** @example Welcome */
			title: string;
			/** @example Cover Craft */
			subtitle?: string;
			/** @example cover */
			filename: string;
		};
		ValidationError: {
			/** @example width */
			field: string;
			/** @example Width must be between 1 and 1200 */
			message: string;
		};
		ValidationErrorResponse: {
			/** @example Validation failed */
			error: string;
			details: components["schemas"]["ValidationError"][];
		};
		ErrorResponse: {
			/** @example Internal server error */
			error: string;
		};
		MetricPayload: {
			/** @example image_generated */
			event: string;
			/** Format: date-time */
			timestamp: string;
			/** @enum {string} */
			status: "success" | "error" | "validation_error";
			errorMessage?: string;
			size?: {
				width: number;
				height: number;
			};
			font?: string;
			titleLength?: number;
			subtitleLength?: number;
			contrastRatio?: number;
			/** @enum {string} */
			wcagLevel?: "AAA" | "AA" | "FAIL";
			duration?: number;
			clientDuration?: number;
		};
		JobStatusResponse: {
			id: string;
			/** @enum {string} */
			status: "pending" | "processing" | "completed" | "failed";
			progress: number;
			total: number;
			results: string[];
			error?: string;
			/** Format: date-time */
			createdAt: string;
			/** Format: date-time */
			updatedAt: string;
		};
		/** @description Dashboard analytics details (feature popularity, accessibility, engagement) */
		AnalyticsResult: {
			userEngagement: Record<string, never>;
			featurePopularity: Record<string, never>;
			accessibilityCompliance: Record<string, never>;
			performanceMetrics: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
