name: API - PR Build & Test Check

on:
  pull_request:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "api/"
  NODE_VERSION: "22.x"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm install
          popd

      - name: Build Project
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm run build
          popd

      - name: Run Tests
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          npm run test -- --run
          popd
