name: API - Biome Format Check

on:
  pull_request:
    paths:
      - 'api/**'

jobs:
  api-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '22.x'
      - uses: victoriacheng15hub/platform-actions/biome-format@main
        with:
          path: 'api/**'
