name: Biome Format Check

on:
  pull_request:
    paths:
      - 'api/**'

jobs:
  api-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '22'
      - uses: victoriacheng15hub/platform-actions/biome-format@main
        with:
          path: 'api/**'
