name: Frontend - Biome Format Check

on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '22.x'
      - name: Run Biome check
        run: npm run lint
